#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HarmNumb.Resource", IsApplication=true)]

namespace HarmNumb
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int harm_numb_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int harm_numb_color_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int keyA = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int keyAb = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int keyB = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int keyBb = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int keyC = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int keyD = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int keyDb = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int keyE = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int keyEb = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int keyF = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int keyFSharp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int keyG = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int keyGb = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btn_nr_1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btn_nr_2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int btn_nr_3 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btn_nr_4 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int btn_nr_5 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btn_nr_6 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int btn_nr_7 = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int img_key = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int txt_harm_number = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int txt_key = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int txt_timer = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HarmNumbTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
